(define (problem book-plan-25)
  (:domain book-plan)
  (:objects
    Book0 Book1 Book2 Book3 Book4 Book5 Book6 Book7 Book8 Book9 Book10 Book11 Book12 Book13 Book14 Book15 Book16 Book17 Book18 Book19 Book20 Book21 Book22 Book23 Book24 - Book ; List all the books
    Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec - Month ; List all the months
  )

  (:init
    (predecessor Book0 Book8) 
    (predecessor Book0 Book19)
    (predecessor Book0 Book21)
    (predecessor Book0 Book23)
    (predecessor Book0 Book24)
    (predecessor Book1 Book3)
    (predecessor Book1 Book4)
    (predecessor Book1 Book6)
    (parallel Book1 Book11)
    (predecessor Book1 Book13)
    (predecessor Book1 Book17)
    (predecessor Book1 Book24)
    (predecessor Book2 Book10)
    (predecessor Book2 Book13)
    (predecessor Book2 Book17)
    (predecessor Book2 Book24)
    (predecessor Book3 Book4)
    (parallel Book3 Book7)
    (parallel Book3 Book8)
    (predecessor Book3 Book10)
    (predecessor Book3 Book12)
    (predecessor Book3 Book14)
    (predecessor Book3 Book16)
    (parallel Book3 Book17)
    (parallel Book3 Book21)
    (predecessor Book3 Book24)
    (predecessor Book4 Book8)
    (predecessor Book4 Book9)
    (parallel Book4 Book11)
    (predecessor Book4 Book14)
    (predecessor Book4 Book22)
    (predecessor Book4 Book23)
    (parallel Book5 Book7)
    (predecessor Book5 Book8)
    (predecessor Book5 Book10)
    (predecessor Book5 Book11)
    (predecessor Book5 Book12)
    (predecessor Book5 Book21)
    (predecessor Book5 Book23)
    (predecessor Book6 Book7)
    (predecessor Book6 Book19)
    (predecessor Book6 Book22)
    (predecessor Book7 Book13)
    (predecessor Book7 Book16)
    (predecessor Book7 Book22)
    (predecessor Book8 Book9)
    (parallel Book8 Book12)
    (predecessor Book8 Book13)
    (predecessor Book8 Book16)
    (predecessor Book8 Book20)
    (predecessor Book8 Book23)
    (parallel Book8 Book24)
    (predecessor Book9 Book17)
    (predecessor Book9 Book19)
    (predecessor Book10 Book11)
    (predecessor Book10 Book13)
    (predecessor Book10 Book15)
    (parallel Book10 Book20)
    (predecessor Book10 Book24)
    (parallel Book11 Book20)
    (parallel Book11 Book22)
    (parallel Book11 Book23)
    (parallel Book12 Book15)
    (predecessor Book12 Book22)
    (predecessor Book12 Book24)
    (predecessor Book13 Book16)
    (predecessor Book13 Book20)
    (predecessor Book13 Book21)
    (parallel Book14 Book16)
    (parallel Book14 Book21)
    (parallel Book15 Book16)
    (predecessor Book15 Book19)
    (predecessor Book15 Book20)
    (predecessor Book15 Book22)
    (predecessor Book15 Book23)
    (parallel Book16 Book17)
    (predecessor Book16 Book20)
    (predecessor Book16 Book22)
    (predecessor Book17 Book20)
    (predecessor Book17 Book21)
    (parallel Book17 Book23)
    (predecessor Book17 Book24)
    (predecessor Book18 Book19)
    (predecessor Book18 Book21)
    (predecessor Book18 Book22)
    (predecessor Book19 Book20)
    (predecessor Book19 Book22)
    (predecessor Book20 Book21)
    (predecessor Book20 Book24)
    (predecessor Book21 Book23)
    (predecessor Book23 Book24)
    (goal Book0)
    (goal Book4)
    (goal Book5)
    (goal Book9)
    (goal Book11)
    (goal Book15)
    (goal Book17)
    (goal Book19)
    (goal Book21)
    (goal Book24)
    (read Book2)
    (before Jan Feb)
    (before Jan Mar)
    (before Jan Apr)
    (before Jan May)
    (before Jan Jun)
    (before Jan Jul)
    (before Jan Aug)
    (before Jan Sep)
    (before Jan Oct)
    (before Jan Nov)
    (before Jan Dec)
    (before Feb Mar)
    (before Feb Apr)
    (before Feb May)
    (before Feb Jun)
    (before Feb Jul)
    (before Feb Aug)
    (before Feb Sep)
    (before Feb Oct)
    (before Feb Nov)
    (before Feb Dec)
    (before Mar Apr)
    (before Mar May)
    (before Mar Jun)
    (before Mar Jul)
    (before Mar Aug)
    (before Mar Sep)
    (before Mar Oct)
    (before Mar Nov)
    (before Mar Dec)
    (before Apr May)
    (before Apr Jun)
    (before Apr Jul)
    (before Apr Aug)
    (before Apr Sep)
    (before Apr Oct)
    (before Apr Nov)
    (before Apr Dec)
    (before May Jun)
    (before May Jul)
    (before May Aug)
    (before May Sep)
    (before May Oct)
    (before May Nov)
    (before May Dec)
    (before Jun Jul)
    (before Jun Aug)
    (before Jun Sep)
    (before Jun Oct)
    (before Jun Nov)
    (before Jun Dec)
    (before Jul Aug)
    (before Jul Sep)
    (before Jul Oct)
    (before Jul Nov)
    (before Jul Dec)
    (before Aug Sep)
    (before Aug Oct)
    (before Aug Nov)
    (before Aug Dec)
    (before Sep Oct)
    (before Sep Nov)
    (before Sep Dec)
    (before Oct Nov)
    (before Oct Dec)
    (before Nov Dec)
    (sameTime Jan Jan)
    (sameTime Feb Feb)
    (sameTime Mar Mar)
    (sameTime Apr Apr)
    (sameTime May May)
    (sameTime Jun Jun)
    (sameTime Jul Jul)
    (sameTime Aug Aug)
    (sameTime Sep Sep)
    (sameTime Oct Oct)
    (sameTime Nov Nov)
    (sameTime Dec Dec)
  )

  (:goal
    (not (exists (?b - Book)
      (and (goal ?b) (not (read ?b)))))
  )
)